<?php if ($this->pageCount): ?>
    <div class="paginationControl">
        <span class="resumPaginator">   <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
            de <?php echo $this->totalItemCount; ?> Totales
        </span>
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a href="/productos/<?php echo $this->slugCategoria; ?>/<?php echo $this->slugSubCategoria; ?>/page/<?php echo $this->previous; ?>">    
                &lt; Previous
            </a> 
        <?php else: ?>
            <span class="disabled">&lt; Previous</span> 
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="/productos/<?php echo $this->slugCategoria; ?>/<?php echo $this->slugSubCategoria; ?>/page/<?php echo $page ?>">    
                    <?php echo $page; ?>
                </a> 
            <?php else: ?>
                <span class="page select"><?php echo $page; ?> </span>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <a href="/productos/<?php echo $this->slugCategoria; ?>/<?php echo $this->slugSubCategoria; ?>/page/<?php echo $this->next; ?>">    
                Next &gt;
            </a>
        <?php else: ?>
            <span class="disabled">Next &gt;</span>
        <?php endif; ?>
    </div>
<?php endif; ?>

