<!-- Start: login-holder -->
<div id="login-holder">

	<!-- start logo -->
	<div id="logo-login">
		<a href="index.html"><img src="images/shared/logo.png" width="156" height="40" alt="" /></a>
	</div>
	<!-- end logo -->
	
	<div class="clear"></div>
	
	<!--  start loginbox ................................................................................. -->
	<div id="loginbox">
	
	<!--  start login-inner -->
	<div id="login-inner">
            <form id="frm_delete" method="post" action="/admin/panel/">
              
		<table border="0" cellpadding="0" cellspacing="0">
		<tr>
			<th>Username</th>
			<td><input type="text" id="usuario" name="usuario" onfocus="this.value=''" class="login-inp" /></td>
		</tr>
		<tr>
			<th>Password</th>
			<td><input type="password" id="password" name="password" class="login-inp" /></td>
		</tr>
		<tr>
			<th></th>
                </tr>
		<tr>
			<th></th>
                        <td><input type="submit"  class="submit-login" /></td>
		</tr>
		</table>
            </form>
	</div>
 	<!--  end login-inner -->
	<div class="clear"></div>
	<a href="" class="forgot-pwd"></a>
 </div>
 <!--  end loginbox -->

</div>
<!-- End: login-holder -->
