<!-- Start: login-holder -->
<div id="login-holder">

	<!-- start logo -->
	<div id="logo-login">
		<a href="index.html"><img src="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/images/shared/logo.png" width="156" height="40" alt="" /></a>
	</div>
	<!-- end logo -->
	
	<div class="clear"></div>
	
	<!--  start loginbox ................................................................................. -->
	<div id="loginbox">
	
	<!--  start login-inner -->
	<div id="login-inner">
            <form id="formLogin" method="post" action="/admin/">
              <?php
                echo $this->formLoginAdmin ;
                ?>
		<!--<table border="0" cellpadding="0" cellspacing="0">
		<tr>
			<th>Username</th>
			<td><input type="text" id="Usuario" name="Usuario" onfocus="this.value=''" class="login-inp" /></td>
		</tr>
		<tr>
			<th>Password</th>
			<td><input type="password" id="Password" name="Password" class="login-inp" /></td>
		</tr>
		<tr>
			<th></th>
                </tr>
		<tr>
			<th></th>
                        <td><input type="submit"  class="submit-login" /></td>
		</tr>
		</table>-->
            </form>
	</div>
 	<!--  end login-inner -->
	<div class="clear"></div>
	<a href="" class="forgot-pwd"></a>
 </div>
 <!--  end loginbox -->

</div>
<!-- End: login-holder -->
