<div class="grid_5" >
    Columna Izquierda
    <?php
    $pagerData = array(
        'getPathInfo' => $this->getPathInfo,
        'listaCategoriasNavigator' => $this->listaCategoriasNavigator
    );
    echo $this->partial('/partial/menucategorias.phtml', $pagerData)
    ?>
</div>
<div class="grid_19" >
    Columna Derecha
    <div class="block_content">
        <?php
        $params = array('slug' => $this->slug);
        echo $paginator = $this->paginationControl($this->productos, 'Sliding', '/paginator/ProductFor.phtml', $params);
        $params = array('productos'=>$this->productos,'paginator'=>$paginator);
        echo $this->partial('/partial/listaProductosPaginator.phtml', $params)
        ?>
         
    </div>               
</div>

