
<div class="std"><script type="text/javascript" src="static/js/jquery.js"></script>
    <script type="text/javascript" src="static/js/tms-0.js"></script>
    <script type="text/javascript" src="static/js/tms_presets.js"></script>

    <script type="text/javascript">
        ;(function($){
			
            $(window).load(function(){
                $('.slider')._TMS({
                    prevBu:'.prev',
                    nextBu:'.next',
                    playBu:'.play',
                    duration:800,
                    easing:'easeOutQuad',
                    preset:'simpleFade',
                    pagination:true,
                    //pagNums:false,
                    slideshow:5000,
                    numStatus:false,
                    banners:'fade',// fromLeft, fromRight, fromTop, fromBottom
                    waitBannerAnimation:false
                })	
            })
		
        })(jQuery)
    </script>

    <div style="z-index: 1; overflow: hidden;" class="slider">
        <ul class="items">	
            <li>
                <img alt="" src="static/slide1.jpg"/>

            </li>
            <li>
                <img alt="" src="static/slide2.jpg"/>

            </li>
            <li>
                <img alt="" src="static/slide3.jpg"/>

            </li>
        </ul>
        <div style="overflow: hidden; width: 630px; height: 338px; background: url(&quot;http://livedemo00.template-help.com/magento_39583/skin/frontend/default/theme354/images/media/slide2.jpg&quot;) no-repeat scroll 0px 0px transparent;" class="pic">
            <div style="position: absolute; width: 100%; height: 100%; left: 0px; top: 0px; z-index: 1;" class="mask">
                <div style="left: 0px; top: 0px; position: absolute; width: 630px; height: 338px; background-position: 0px 0px; background-image: url(&quot;http://livedemo00.template-help.com/magento_39583/skin/frontend/default/theme354/images/media/slide2.jpg&quot;); opacity: 1; display: none;">
                </div>
            </div>
        </div>
        <ul class="pagination">
            <li class="">
                <a href="#">1</a>
            </li>
            <li class="current">
                <a href="#">2</a>
            </li>
            <li class="">
                <a href="#">3</a>
            </li>
        </ul>
        <div style="z-index: 999; opacity: 0;" class="banner">
            <a href="http://livedemo00.template-help.com/magento_39583/storage.html/">
                &nbsp;
            </a>
        </div>
        <div style="z-index: 999; opacity: 0;" class="banner">
            <a href="http://livedemo00.template-help.com/magento_39583/workstations.html/">
                &nbsp;
            </a>
        </div>
        <div style="z-index: 999; opacity: 1;" class="banner">
            <a href="http://livedemo00.template-help.com/magento_39583/servers.html/">
                &nbsp;
            </a>
        </div>
    </div>
    <div class="banners">
        <a href="http://livedemo00.template-help.com/magento_39583/networking/entertainment-networking.html/"><img alt="" src="static/banner1.jpg"/></a>
    </div></div><div class="main-border">
    <div class="page-title"><h1>Nuevos Productos</h1></div>
    
    <?php
    $count = 1;
    $filaActual = 1;
    
    $countProducto = count($this->productosDestacados);
    $cantFila = $countProducto>=4?((int)($countProducto/4)):1;
    $reset=4;
    if($countProducto<4){
        $reset = $countProducto;
    }
    $resUltimaFila = $countProducto>=4?((int)($countProducto%4)):0;
    if($resUltimaFila>0){
        $cantFila++;
    }
    foreach ($this->productosDestacados as $index):
        if($resUltimaFila>0){
            if($filaActual==$cantFila){
                $reset=$resUltimaFila;
            }
        }
    switch ($count) {
            case 1:
                $classLimit = 'first';
                break;
            case 2:
                $classLimit = '';
                break;
            case 3:
                $classLimit = '';
                break;
            case 4:
                $classLimit = 'last';
                break;
        } 
    ?>
    <?php if ($count == 1) {
            ?>
            <ul class="products-grid">
    <?php } ?>
    
        
        <li class="item <?php echo $classLimit ?>">
            <a href="http://livedemo00.template-help.com/magento_39583/toshiba-250-gb-usb-2-0-portable-external-hard-drive-hddr250e03x.html" title="Toshiba 250 GB USB 2.0 Portable External Hard Drive" class="product-image"><img src="static/file_2_6.jpg" alt="Toshiba 250 GB USB 2.0 Portable External Hard Drive" height="130" width="130"/></a>
            <h3 class="product-name"><a href="http://livedemo00.template-help.com/magento_39583/toshiba-250-gb-usb-2-0-portable-external-hard-drive-hddr250e03x.html" title="Toshiba 250 GB USB 2.0 Portable External Hard Drive">Toshiba 250 GB USB 2.0 Portabl...</a></h3>
            <div class="price-box">
                <span class="regular-price" id="product-price-7-new">
                    <span class="price">$500.00</span>                                    </span>

            </div>

            <div class="actions">
                <button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://livedemo00.template-help.com/magento_39583/toshiba-250-gb-usb-2-0-portable-external-hard-drive-hddr250e03x.html?options=cart')"><span><span>Add to Cart</span></span></button>
                <a class="button2" href="http://livedemo00.template-help.com/magento_39583/toshiba-250-gb-usb-2-0-portable-external-hard-drive-hddr250e03x.html"><span><span>Details</span></span></a>
            </div>
        </li>
        
        <?php if ($count == $reset) {
            $filaActual++;
            $count = 0; ?>
            </ul>
        <?php } ?>

        <?php
        $count++;
    endforeach;
    ?>
    
    
</div>