
<div class="std"><script type="text/javascript" src="static/js/jquery.js"></script>
    <script type="text/javascript" src="static/js/tms-0.js"></script>
    <script type="text/javascript" src="static/js/tms_presets.js"></script>

    <script type="text/javascript">
        ;(function($){
			
            $(window).load(function(){
                $('.slider')._TMS({
                    prevBu:'.prev',
                    nextBu:'.next',
                    playBu:'.play',
                    duration:800,
                    easing:'easeOutQuad',
                    preset:'simpleFade',
                    pagination:true,
                    //pagNums:false,
                    slideshow:5000,
                    numStatus:false,
                    banners:'fade',// fromLeft, fromRight, fromTop, fromBottom
                    waitBannerAnimation:false
                })	
            })
		
        })(jQuery)
    </script>

    <div style="z-index: 1; overflow: hidden;" class="slider">
        <ul class="items">	
            <li>
                <img alt="" src="static/slide1.jpg"/>

            </li>
            <li>
                <img alt="" src="static/slide2.jpg"/>

            </li>
            <li>
                <img alt="" src="static/slide3.jpg"/>

            </li>
        </ul>
        <div style="overflow: hidden; width: 630px; height: 338px; background: url(&quot;http://livedemo00.template-help.com/magento_39583/skin/frontend/default/theme354/images/media/slide2.jpg&quot;) no-repeat scroll 0px 0px transparent;" class="pic">
            <div style="position: absolute; width: 100%; height: 100%; left: 0px; top: 0px; z-index: 1;" class="mask">
                <div style="left: 0px; top: 0px; position: absolute; width: 630px; height: 338px; background-position: 0px 0px; background-image: url(&quot;http://livedemo00.template-help.com/magento_39583/skin/frontend/default/theme354/images/media/slide2.jpg&quot;); opacity: 1; display: none;">
                </div>
            </div>
        </div>
        <ul class="pagination">
            <li class="">
                <a href="#">1</a>
            </li>
            <li class="current">
                <a href="#">2</a>
            </li>
            <li class="">
                <a href="#">3</a>
            </li>
        </ul>
        <div style="z-index: 999; opacity: 0;" class="banner">
            <a href="http://livedemo00.template-help.com/magento_39583/storage.html/">
                &nbsp;
            </a>
        </div>
        <div style="z-index: 999; opacity: 0;" class="banner">
            <a href="http://livedemo00.template-help.com/magento_39583/workstations.html/">
                &nbsp;
            </a>
        </div>
        <div style="z-index: 999; opacity: 1;" class="banner">
            <a href="http://livedemo00.template-help.com/magento_39583/servers.html/">
                &nbsp;
            </a>
        </div>
    </div>
    <div class="banners">
        <a href="http://livedemo00.template-help.com/magento_39583/networking/entertainment-networking.html/"><img alt="" src="static/banner1.jpg"/></a>
    </div></div><div class="main-border">
    <div class="page-title"><h1>Nuevos Productos</h1></div>
    <ul class="products-grid">
        <li class="item first">
            <a href="http://livedemo00.template-help.com/magento_39583/toshiba-250-gb-usb-2-0-portable-external-hard-drive-hddr250e03x.html" title="Toshiba 250 GB USB 2.0 Portable External Hard Drive" class="product-image"><img src="static/file_2_6.jpg" alt="Toshiba 250 GB USB 2.0 Portable External Hard Drive" height="130" width="130"/></a>
            <h3 class="product-name"><a href="http://livedemo00.template-help.com/magento_39583/toshiba-250-gb-usb-2-0-portable-external-hard-drive-hddr250e03x.html" title="Toshiba 250 GB USB 2.0 Portable External Hard Drive">Toshiba 250 GB USB 2.0 Portabl...</a></h3>
            <div class="price-box">
                <span class="regular-price" id="product-price-7-new">
                    <span class="price">$500.00</span>                                    </span>

            </div>

            <div class="actions">
                <button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://livedemo00.template-help.com/magento_39583/toshiba-250-gb-usb-2-0-portable-external-hard-drive-hddr250e03x.html?options=cart')"><span><span>Add to Cart</span></span></button>
                <a class="button2" href="http://livedemo00.template-help.com/magento_39583/toshiba-250-gb-usb-2-0-portable-external-hard-drive-hddr250e03x.html"><span><span>Details</span></span></a>
            </div>
        </li>
        <li class="item">
            <a href="http://livedemo00.template-help.com/magento_39583/hp-pavilion-slimline-s3700f-workstation.html" title="HP Pavilion Slimline S3700F Workstation" class="product-image"><img src="static/file_1_28.jpg" alt="HP Pavilion Slimline S3700F Workstation" height="130" width="130"/></a>
            <h3 class="product-name"><a href="http://livedemo00.template-help.com/magento_39583/hp-pavilion-slimline-s3700f-workstation.html" title="HP Pavilion Slimline S3700F Workstation">HP Pavilion Slimline S3700F Wo...</a></h3>



            <div class="price-box">
                <span class="regular-price" id="product-price-29-new">
                    <span class="price">$3,300.59</span>                                    </span>

            </div>

            <div class="actions">
                <button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://livedemo00.template-help.com/magento_39583/hp-pavilion-slimline-s3700f-workstation.html?options=cart')"><span><span>Add to Cart</span></span></button>
                <a class="button2" href="http://livedemo00.template-help.com/magento_39583/hp-pavilion-slimline-s3700f-workstation.html"><span><span>Details</span></span></a>
            </div>
        </li>
        <li class="item">
            <a href="http://livedemo00.template-help.com/magento_39583/compaq-cq2009f-workstation.html" title="Compaq CQ2009F Workstation" class="product-image">
                <img src="static/file_3_10.jpg" alt="Compaq CQ2009F Workstation" height="130" width="130"/>
            </a>
            <h3 class="product-name"><a href="http://livedemo00.template-help.com/magento_39583/compaq-cq2009f-workstation.html" title="Compaq CQ2009F Workstation">Compaq CQ2009F Workstation...</a></h3>
            <div class="price-box">
                <span class="regular-price" id="product-price-27-new">
                    <span class="price">$5,600.00</span>                                    </span>
            </div>
            <div class="actions">
                <button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://livedemo00.template-help.com/magento_39583/checkout/cart/add/uenc/aHR0cDovL2xpdmVkZW1vMDAudGVtcGxhdGUtaGVscC5jb20vbWFnZW50b18zOTU4My8,/product/27/')"><span><span>Add to Cart</span></span></button>
                <a class="button2" href="http://livedemo00.template-help.com/magento_39583/compaq-cq2009f-workstation.html"><span><span>Details</span></span></a>
            </div>
        </li>
        <li class="item last">
            <a href="http://livedemo00.template-help.com/magento_39583/apple-airport-extreme-base-station-gigabit-mb053ll.html" title="Apple AirPort Extreme Base Station (Gigabit) MB053LL" class="product-image">
                <img src="static/file_3_5.jpg" alt="Apple AirPort Extreme Base Station (Gigabit) MB053LL" height="130" width="130"/>
            </a>
            <h3 class="product-name"><a href="http://livedemo00.template-help.com/magento_39583/apple-airport-extreme-base-station-gigabit-mb053ll.html" title="Apple AirPort Extreme Base Station (Gigabit) MB053LL">Apple AirPort Extreme Base Sta...</a></h3>
            <div class="price-box">
                <span class="regular-price" id="product-price-22-new">
                    <span class="price">$28.99</span>                                    </span>
            </div>

            <div class="actions">
                <button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://livedemo00.template-help.com/magento_39583/checkout/cart/add/uenc/aHR0cDovL2xpdmVkZW1vMDAudGVtcGxhdGUtaGVscC5jb20vbWFnZW50b18zOTU4My8,/product/22/')"><span><span>Add to Cart</span></span></button>
                <a class="button2" href="http://livedemo00.template-help.com/magento_39583/apple-airport-extreme-base-station-gigabit-mb053ll.html"><span><span>Details</span></span></a>
            </div>
        </li>
    </ul>
    <ul class="products-grid">
        <li class="item first">
            <a href="http://livedemo00.template-help.com/magento_39583/tivo-ag0100-wireless-g-usb-network-adapter.html" title="TiVo AG0100 Wireless G USB Network Adapter" class="product-image"><img src="static/file_10.jpg" alt="TiVo AG0100 Wireless G USB Network Adapter" height="130" width="130"></a>
            <h3 class="product-name"><a href="http://livedemo00.template-help.com/magento_39583/tivo-ag0100-wireless-g-usb-network-adapter.html" title="TiVo AG0100 Wireless G USB Network Adapter">TiVo AG0100 Wireless G USB Net...</a></h3>



            <div class="price-box">
                <span class="regular-price" id="product-price-9-new">
                    <span class="price">$50.00</span>                                    </span>

            </div>

            <div class="actions">
                <button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://livedemo00.template-help.com/magento_39583/checkout/cart/add/uenc/aHR0cDovL2xpdmVkZW1vMDAudGVtcGxhdGUtaGVscC5jb20vbWFnZW50b18zOTU4My8,/product/9/')"><span><span>Add to Cart</span></span></button>
                <a class="button2" href="http://livedemo00.template-help.com/magento_39583/tivo-ag0100-wireless-g-usb-network-adapter.html"><span><span>Details</span></span></a>
            </div>
        </li>
        <li class="item">
            <a href="http://livedemo00.template-help.com/magento_39583/hp-pavilion-a6750f-workstation.html" title="HP Pavilion A6750F Workstation" class="product-image"><img src="static/file_1_27.jpg" alt="HP Pavilion A6750F Workstation" height="130" width="130"></a>
            <h3 class="product-name"><a href="http://livedemo00.template-help.com/magento_39583/hp-pavilion-a6750f-workstation.html" title="HP Pavilion A6750F Workstation">HP Pavilion A6750F Workstation...</a></h3>



            <div class="price-box">
                <span class="regular-price" id="product-price-28-new">
                    <span class="price">$4,300.00</span>                                    </span>

            </div>

            <div class="actions">
                <button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://livedemo00.template-help.com/magento_39583/checkout/cart/add/uenc/aHR0cDovL2xpdmVkZW1vMDAudGVtcGxhdGUtaGVscC5jb20vbWFnZW50b18zOTU4My8,/product/28/')"><span><span>Add to Cart</span></span></button>
                <a class="button2" href="http://livedemo00.template-help.com/magento_39583/hp-pavilion-a6750f-workstation.html"><span><span>Details</span></span></a>
            </div>
        </li>
        <li class="item">
            <a href="http://livedemo00.template-help.com/magento_39583/buypower-gamer-extreme-ko-969.html" title="BUYPOWER Gamer Extreme KO-969" class="product-image"><img src="static/file_29.jpg" alt="BUYPOWER Gamer Extreme KO-969" height="130" width="130"></a>
            <h3 class="product-name"><a href="http://livedemo00.template-help.com/magento_39583/buypower-gamer-extreme-ko-969.html" title="BUYPOWER Gamer Extreme KO-969">BUYPOWER Gamer Extreme KO-969...</a></h3>



            <div class="price-box">
                <span class="regular-price" id="product-price-26-new">
                    <span class="price">$8,000.00</span>                                    </span>

            </div>

            <div class="actions">
                <button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://livedemo00.template-help.com/magento_39583/buypower-gamer-extreme-ko-969.html?options=cart')"><span><span>Add to Cart</span></span></button>
                <a class="button2" href="http://livedemo00.template-help.com/magento_39583/buypower-gamer-extreme-ko-969.html"><span><span>Details</span></span></a>
            </div>
        </li>
        <li class="item last">
            <a href="http://livedemo00.template-help.com/magento_39583/roku-soundbridge-m1000-network-music-system.html" title="Roku SoundBridge M1000 Network Music System" class="product-image"><img src="static/file_13.jpg" alt="Roku SoundBridge M1000 Network Music System" height="130" width="130"></a>
            <h3 class="product-name"><a href="http://livedemo00.template-help.com/magento_39583/roku-soundbridge-m1000-network-music-system.html" title="Roku SoundBridge M1000 Network Music System">Roku SoundBridge M1000 Network...</a></h3>



            <div class="price-box">
                <span class="regular-price" id="product-price-12-new">
                    <span class="price">$45.69</span>                                    </span>

            </div>

            <div class="actions">
                <button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://livedemo00.template-help.com/magento_39583/roku-soundbridge-m1000-network-music-system.html?options=cart')"><span><span>Add to Cart</span></span></button>
                <a class="button2" href="http://livedemo00.template-help.com/magento_39583/roku-soundbridge-m1000-network-music-system.html"><span><span>Details</span></span></a>
            </div>
        </li>
    </ul>
</div>