<div class="page-title category-title">
    <h1><?php echo $this->title==''?'Productos':$this->title; ?></h1>
</div>
<?php
$count = 1;
?>

<?php if (count($this->productos) > 0) { ?>
<div class="category-products">
    <div class="toolbar">
        <div class="pager">
            <p class="amount">
                <strong><?php echo $this->productos->getCurrentItemCount(); ?> Item(s)</strong>
            </p>
            <?php
            echo $this->paginator;
            ?>
        </div>
        <div class="sorter">
            <div class="sort-by">
            </div>
        </div>
    </div>


    <?php
    foreach ($this->productos as $index):
        switch ($count) {
            case 1:
                $classLimit = 'first';
                break;
            case 2:
                $classLimit = '';
                break;
            case 3:
                $classLimit = 'last';
                break;
        }

        if ($count == 1) {
            ?>
            <ul class="products-grid first odd">
    <?php } ?>
            <li class="item <?php echo $classLimit ?>">
                <a href="<?php echo $this->baseUrl(); ?>/productos/detalle-producto/<?php echo $index['Slug'] ?>" title="<?php echo $index['Nombre'] ?>" class="product-image">
    <!--                <img src="http://livedemo00.template-help.com/magento_39583/media/catalog/product/cache/5/small_image/160x/9df78eab33525d08d6e5fb8d27136e95/f/i/file_1.jpg" width="160" height="160" alt="HP EX487 MediaSmart Home Server"/>-->
                    <img src="<?php echo CST_Server_ServerDinamic::getUrl(); ?>/imagen-producto/<?php echo $index['Imagen'] ?>?<?php echo rand(0, 1000); ?>" alt="<?php echo $index['Nombre'] ?>" width="160" height="160" />
                </a>
                <h2 class="product-name"><a href="<?php echo $this->baseUrl(); ?>/productos/detalle-producto/<?php echo $index['Slug'] ?>" title="<?php echo $index['Nombre'] ?>"><?php echo $index['Nombre'] ?></a></h2>

    <?php if ($index['FlagOferta'] == 1) { ?>
                    <span class="old-price" id="product-price-2">
                        <span class="price"><?php echo $index['PrecioOferta'] ?></span>
                    </span><?php } ?>


                <div class="info">
                    <div class="price-box">
                        <span class="regular-price" id="product-price-1">
                            <span class="price">$ <?php echo $index['PrecioVenta'] ?></span>                                    </span>
                    </div>
                    <form name="form_list_<?php echo $index['IdProducto'] ?>" action="/carrito-compras/registrar-producto/<?php echo $index['IdProducto'] ?>" method="Post">
                        <button type="button" title="Add to Cart" class="button btn-cart" onclick="form_list_<?php echo $index['IdProducto']; ?>.submit(this)"><span><span>Add to Cart</span></span></button>
                        <input type="hidden" name="cantidad" value="1" />
                        <input type="hidden" id="hidden_idproducto_<?php echo $index['IdProducto'] ?>" name="slugProducto" value="<?php echo $index['Slug'] ?>" />
                    </form>
                    
                </div>
                <div class="actions">
                    <ul class="add-to-links">
                        <li><a href="<?php echo $this->baseUrl(); ?>/productos/detalle-producto/<?php echo $index['Slug'] ?>" class="link-wishlist">Ver mas</a></li>

                    </ul>
                </div>
            </li>
        <?php if ($count == 3) {
            $count = 0; ?>
            </ul>
        <?php } ?>

        <?php
        $count++;
    endforeach;
    ?>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <div class="clear" ></div>
    <div class="toolbar-bottom">
        <div class="toolbar">
            <div class="pager">
                <p class="amount">
                    <strong><?php echo $this->productos->getCurrentItemCount(); ?> Item(s)</strong>
                </p>
<?php echo $this->paginator; ?>
            </div>
            <div class="sorter">
                <div class="sort-by">
                </div>
            </div>
        </div>
    </div>
</div>
<div id="map-popup" class="map-popup" style="display:none;">
    <a href="#" class="map-popup-close" id="map-popup-close">x</a>
    <div class="map-popup-arrow"></div>
    <div class="map-popup-heading"><h2 id="map-popup-heading"></h2></div>
    <div class="map-popup-content" id="map-popup-content">
        <div class="map-popup-checkout">
            <form action="" method="POST" id="product_addtocart_form_from_popup">
                <input type="hidden" name="product" class="product_id" value="" id="map-popup-product-id">
                <div class="additional-addtocart-box">
                </div>
                <button type="button" title="Add to Cart" class="button btn-cart" id="map-popup-button"><span><span>Add to Cart</span></span></button>
            </form>
        </div>
        <div class="map-popup-msrp" id="map-popup-msrp-box"><strong>Price:</strong> <span style="text-decoration:line-through;" id="map-popup-msrp"></span></div>
        <div class="map-popup-price" id="map-popup-price-box"><strong>Actual Price:</strong> <span id="map-popup-price"></span></div>
        <script type="text/javascript">
            //<![CDATA[
            document.observe("dom:loaded", Catalog.Map.bindProductForm);
            //]]>
        </script>
    </div>
    <div class="map-popup-text" id="map-popup-text">Our price is lower than the manufacturer's "minimum advertised price."  As a result, we cannot show you the price in catalog or the product page. <br><br> You have no obligation to purchase the product once you know the price. You can simply remove the item from your cart.</div>
    <div class="map-popup-text" id="map-popup-text-what-this">Our price is lower than the manufacturer's "minimum advertised price."  As a result, we cannot show you the price in catalog or the product page. <br><br> You have no obligation to purchase the product once you know the price. You can simply remove the item from your cart.</div>
</div>


    
    
<?php } else { ?>    
    No se encontro ningun producto
<?php } ?> 