<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" xmlns:fb="http://ogp.me/ns/fb#"> 
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headStyle() ?>
        <link rel="stylesheet" type="text/css" href="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/css/datePicker.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/css/pro_dropline.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/css/pro_dropline_ie.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/css/screen.css"/>
        <?php echo $this->headLink() ?>
        <script src="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/js/custom_jquery.js"></script>
        <script src="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/js/date.js"></script>
        <script src="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/js/jquery-1.4.1.min.js"></script>
        <script src="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/js/jquery.bind.js"></script>
        <script src="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/js/jquery.dimensions.js"></script>
        <script src="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/js/jquery.filestyle.js"></script>
        <script src="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/js/jquery.pngFix.pack.js"></script>
        <script src="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/js/jquery.selectbox-0.5.js"></script>
        <script src="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/js/jquery.selectbox-0.5_style_2.js"></script>
        <script src="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/js/jquery.selectbox-0.5_style_3.js"></script>
        <script src="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/js/jquery.tooltip.js"></script>
        <script src="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/js/jquery.usermode.js"></script>
        <script src="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/js/ui.checkbox.js"></script>
        <script src="<?php echo CST_Server_ServerStaticAdmin::getUrl(); ?>/js/ui.core.js"></script>
        
        <?php echo $this->headScript() ?>
    </head>
    <body id="<?php echo $this->idBody ?>" class="<?php echo $this->classBody ?>" >
        <?php echo $this->layout()->content ?>

    <div class="grid_2">
        <p></p>
    </div>
        
    </body>
</html>