<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" xmlns:fb="http://ogp.me/ns/fb#"> 
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
        
        <link rel="icon" href="http://livedemo00.template-help.com/magento_39583/skin/frontend/default/theme354/favicon.ico" type="image/x-icon"/>
        <link rel="shortcut icon" href="http://livedemo00.template-help.com/magento_39583/skin/frontend/default/theme354/favicon.ico" type="image/x-icon"/>
        <link href="<?php echo CST_Server_ServerStatic::getUrl(); ?>/css/css_003.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo CST_Server_ServerStatic::getUrl(); ?>/css/css_002.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo CST_Server_ServerStatic::getUrl(); ?>/css/css.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo CST_Server_ServerStatic::getUrl(); ?>/css/widgets.css" rel="stylesheet" type="text/css" media="all"/>
        <link href="<?php echo CST_Server_ServerStatic::getUrl(); ?>/css/print.css" rel="stylesheet" type="text/css" media="print"/>
        <!--[if lt IE 7]>
        <script type="text/javascript">
        //<![CDATA[
            var BLANK_URL = '<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/blank.html';
            var BLANK_IMG = '<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/spacer.gif';
        //]]>
        </script>
        <![endif]-->
        <script src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/ga.js" async="" type="text/javascript"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/jquery-1.js"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/sidebar_menu.js"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/jquery_002.js"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/scripts.js"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo CST_Server_ServerStatic::getUrl(); ?>/css/styles.css" media="all"/>
        <link rel="stylesheet" type="text/css" href="<?php echo CST_Server_ServerStatic::getUrl(); ?>/css/widgets.css" media="all"/>
        <link rel="stylesheet" type="text/css" href="<?php echo CST_Server_ServerStatic::getUrl(); ?>/css/print.css" media="print"/>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/prototype.js"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/ccard.js"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/validation.js"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/builder.js"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/effects.js"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/dragdrop.js"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/controls.js"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/slider.js"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/js.js"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/form.js"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/menu.js"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/translate.js"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/cookies.js"></script>
        <!--[if lt IE 8]>
        <link rel="stylesheet" type="text/css" href="<?php echo CST_Server_ServerStatic::getUrl(); ?>/css/styles-ie.css" media="all" />
        <![endif]-->
        <!--[if lt IE 7]>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/ds-sleight.js"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/ie6.js"></script>
        <![endif]-->

        <script type="text/javascript">
            //<![CDATA[
            Mage.Cookies.path     = '/magento_39583';
            Mage.Cookies.domain   = '.livedemo00.template-help.com';
            //]]>
        </script>
        <script type="text/javascript">//<![CDATA[
            var Translator = new Translate([]);
            //]]></script>
        <!--[if lt IE 8]> 
                <div style=' clear: both; height: 59px; padding:0 0 0 15px; position: relative;'> 
                    <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
                        <img src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
                    </a>
                </div> 
        <![endif]--> 

        
    </head>
    <body class=" <?php echo $this->classBody; ?>">
        <div class="header-container">
            <div class="header">
                <div class="page">
                    <div class="container2 row">
                        <h1 class="logo">
                            <strong>Gadget online</strong>
                            <a href="http://livedemo00.template-help.com/magento_39583/" title="Gadget online" class="logo">
                                <img src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/logo.gif" alt="Gadget online"/>
                            </a>
                        </h1>
                        <div class="f-right">
                            <div class="block block-currency currency">
                                <div class="block-title">
                                    <strong><span>&nbsp;</span></strong>
                                </div>
                                
                            </div>
                            <div class="clear"></div>
                            <div class="block-cart-header">
                                <h3>Mi carrito</h3>
                                <div class="block-content">
                                    <p class="empty"><a href="http://livedemo00.template-help.com/magento_39583/checkout/cart/"><strong>0</strong> (items)</a></p>
                                </div>
                            </div>
                            <p class="welcome-msg">Bienvenidos a nuestra tienda en línea!</p>			
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="row1">
                        <div class="container">
                            <form id="search_mini_form" action="http://livedemo00.template-help.com/magento_39583/catalogsearch/result/" method="get">
                                <div class="form-search">
                                    <label for="search">Search:</label>
                                    <input autocomplete="off" id="search" name="q" value="Buscar en toda la tienda aquí ..." class="input-text" maxlength="128" type="text"/>
                                    <button type="submit" title="Search" class="button"><span><span>Search</span></span></button>
                                    <div style="display: none;" id="search_autocomplete" class="search-autocomplete"></div>
                                    <script type="text/javascript">
                                        //<![CDATA[
                                        var searchForm = new Varien.searchForm('search_mini_form', 'search', 'Buscar en toda la tienda aquí ...');
                                        searchForm.initAutocomplete('http://livedemo00.template-help.com/magento_39583/catalogsearch/ajax/suggest/', 'search_autocomplete');
                                        //]]>
                                    </script>
                                </div>
                            </form>
                            <?php echo 
                            $this->navigation()->menu()->render();?>
<!--                            <ul class="links">
                                <li class="first">
                                    <a href="http://livedemo00.template-help.com/magento_39583/customer/account/" title="My Account">My Account</a>
                                </li>
                                <li>
                                    <a href="http://livedemo00.template-help.com/magento_39583/wishlist/" title="My Wishlist">My Wishlist</a>
                                </li>
                                <li>
                                    <a href="http://livedemo00.template-help.com/magento_39583/checkout/cart/" title="My Cart" class="top-link-cart">My Cart</a>
                                </li>
                                <li>
                                    <a href="http://livedemo00.template-help.com/magento_39583/checkout/" title="Checkout" class="top-link-checkout">Checkout</a>
                                </li>
                                <li class=" last">
                                    <a href="http://livedemo00.template-help.com/magento_39583/customer/account/login/" title="Log In">Log In</a>
                                </li>
                            </ul>-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="page">
            <div class="wrapper">
                <noscript>
                    <div class="global-site-notice noscript">
                        <div class="notice-inner">
                            <p>
                                <strong>JavaScript seems to be disabled in your browser.</strong><br />
                                You must have JavaScript enabled in your browser to utilize the functionality of this website.                </p>
                        </div>
                    </div>
                </noscript>
                <div class="main-container col1-layout">
                    
                    <?php if($this->breadCrumbs ==''){
                        echo '<div class="breadcrumbs">Estas en: <a href="'.$this->baseUrl().'/"> Inicio </a> &raquo; ' . $this->navigation()
                                ->breadcrumbs()
                                ->setMinDepth(0)
                                ->setLinkLast(true)
                                ->setSeparator(" &raquo; " . PHP_EOL) . '</div><p>';
                    }else{
                        echo '<div class="breadcrumbs">Estas en:  ' .
                                $this->breadCrumbs . '</div><p>';
                    }
                    
                    ?>
                        
                        
                    <div class="main">
                        <div class="col-wrapper">
                            <div class="col-main">
                                <div class="cart">
                                <?php echo $this->layout()->content ?>
                                    </div>
                            </div>
                            
                        
                    </div>
                </div>
                <div class="footer-container">
                    <div class="footer">
                        <div class="container">
                            <div class="col-1">
                                <ul class="social-links">
                                    <li><a href="http://livedemo00.template-help.com/magento_39583/#/"><img alt="" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/icon1.gif"></a></li>
                                    <li><a href="http://livedemo00.template-help.com/magento_39583/#/"><img alt="" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/icon2.gif"></a></li>
                                    <li><a href="http://livedemo00.template-help.com/magento_39583/#/"><img alt="" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/icon3.gif"></a></li>
                                    <li><a href="http://livedemo00.template-help.com/magento_39583/#/"><img alt="" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/icon4.gif"></a></li>
                                    <li><a href="http://livedemo00.template-help.com/magento_39583/#/"><img alt="" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/icon5.gif"></a></li>
                                    <li><a href="http://livedemo00.template-help.com/magento_39583/#/"><img alt="" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/icon6.gif"></a></li>
                                </ul>				</div>
                            <div class="col-2"><div class="container">
                                    <div class="sub-col-1">
                                        <ul class="footer-list">
                                            <li><a href="http://livedemo00.template-help.com/magento_39583/about-magento-demo-store/">About Us</a></li>
                                            <li><a href="http://livedemo00.template-help.com/magento_39583/customer-service/">Customer Service</a></li>
                                            <li><a href="http://livedemo00.template-help.com/magento_39583/catalog/seo_sitemap/category/">Site Map</a></li>
                                            <li><a href="http://livedemo00.template-help.com/magento_39583/catalogsearch/term/popular/">Search Terms</a></li>
                                            <li><a href="http://livedemo00.template-help.com/magento_39583/catalogsearch/advanced/">Advanced Search</a></li>
                                            <li><a href="http://livedemo00.template-help.com/magento_39583/sales/guest/form/">Orders and Returns</a></li>
                                            <li class="last"><a href="http://livedemo00.template-help.com/magento_39583/contacts/">Contact us</a></li>
                                        </ul>
                                    </div>
                                    <div class="sub-col-2">
                                        <ul class="footer-list">
                                            <li><a href="http://livedemo00.template-help.com/magento_39583/#/">Shipping &amp; Returns</a></li>
                                            <li><a href="http://livedemo00.template-help.com/magento_39583/#/">Secure Shopping</a></li>
                                            <li><a href="http://livedemo00.template-help.com/magento_39583/#/">International Shipping</a></li>
                                            <li><a href="http://livedemo00.template-help.com/magento_39583/#/">Affiliates</a></li>
                                            <li class="last"><a href="http://livedemo00.template-help.com/magento_39583/#/">Group Sales</a></li>
                                        </ul>
                                    </div>
                                    <div class="sub-col-3">
                                        <ul class="footer-list">
                                            <li><a href="http://livedemo00.template-help.com/magento_39583/customer/account/login/">Sign In</a></li>
                                            <li><a href="http://livedemo00.template-help.com/magento_39583/checkout/cart/">View Cart</a></li>
                                            <li><a href="http://livedemo00.template-help.com/magento_39583/wishlist/">My Wishlist</a></li>
                                            <li><a href="http://livedemo00.template-help.com/magento_39583/#/">Track My Order</a></li>
                                            <li class="last"><a href="http://livedemo00.template-help.com/magento_39583/#/">Help</a></li>
                                        </ul>
                                    </div>
                                </div></div>
                        </div>
                        <!--{%FOOTER_LINK}-->	   </div>
                    <address>© <script type="text/javascript">var mdate = new Date(); document.write(mdate.getFullYear());</script>2012 Magento Demo Store. All Rights Reserved.</address>
                </div>

            </div>
        </div>

        <!--LIVEDEMO_00 -->

        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-7078796-5']);
            _gaq.push(['_trackPageview']);
            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();</script>



    </body></html>