<div class="grid_5" >Columna Izquierda
<?php
    $pagerData = array(
        'getPathInfo' => $this->getPathInfo,
        'listaCategoriasNavigator' => $this->listaCategoriasNavigator
    );
    echo $this->partial('/partial/menucategorias.phtml', $pagerData)
    ?>
</div>
            <div class="grid_19" >
                <div class ="detailImageProduct">
                    <div id="ImagenPrinc">
                        
                    </div>
                    <div id="listImagen">
                        <div id="imagen">
                            
                        </div>
                    </div>
                    
                    
                </div>
                
                <div>
                    
                </div>
                
                
                Columna Derecha
               <?php 
               /*detalle del producto*/
               print_r($this->detalleProducto);?>
                
               <?php 
               /*lista de productos relacionados*/
               print_r($this->productosRelacionados);
               
               ?>
            </div>