<div class="grid_19" >
    Columna Derecha
    <div class="block_content">
        <?php
        $params = array(
            'slugSubCategoria' => $this->slugSubCategoria,
            'slugCategoria' => $this->slugCategoria
                );
        echo $paginator = $this->paginationControl($this->productos, 'Sliding', '/paginator/ProductForSubCategorias.phtml', $params);
        $params = array('productos'=>$this->productos,'paginator'=>$paginator);
        echo $this->partial('/partial/listaProductosPaginator.phtml', $params)
        ?>
              
    </div>               
</div>

