<div class="grid_24" >
    <?php $precioTotal = 0;?>
    <div id="titleItemProduct">
        
        <?php 
        $countTotal = count($this->listaCarrito);
        if($countTotal>1){ ?>
        Tienes <?php echo $countTotal; ?> productos en tu carrito
        <?php } else{ ?>
        Tienes <?php echo $countTotal; ?> producto en tu carrito
        <?php }  ?>
    </div>
    <ul id="ListProduct">
        <?php foreach ($this->listaCarrito as $index => $valor) {
            ?>
            <li id="ItemCarrito_<?php echo $index ?>">
                <form id="form_pres_<?php echo $valor['IdProducto'] ?>" action="/carrito-compras/registrar-producto" method="Post">
                    <input type="hidden" id="hidden_idproducto_<?php echo $valor['IdProducto'] ?>" name="slugProducto" value="<?php echo $valor['Slug'] ?>" />
                    <div class="ItemCarritoImagen"><img src="<?php echo CST_Server_ServerDinamic::getUrl() ?>/img/imagen-producto/<?php echo $valor['Imagen'] ?>" /></div>
                    <div class="ItemCarritoNombre">
                        <div><?php echo $valor['Nombre'] ?></div>
                        <div><?php echo $valor['Descripcion'] ?></div>
                        <div>Precio Unitario: <span class="precioUnitario"><?php echo $valor['PrecioVenta'] ?></span></div>
                    </div>
                    <div class="ItemCarritoCantidad"><input type="text" value="<?php echo $valor['cantidad'] ?>" name="cantidadTotal"/></div>
                    <div class="ItemCarritoSumRest">
                        <a id="AumentarCarrito" href="/carrito-compras/aumentar-producto/indice/<?php echo $index ?>"><span class="ui-icon ui-icon-plus"></span></a>
                        <a id="DisminuirCarrito" href="/carrito-compras/disminuir-producto/indice/<?php echo $index ?>"><span class="ui-icon ui-icon-minus"></span></a>
                    </div>
                    <div class="precioTotal"><?php echo $precioItem = $valor['PrecioVenta']*$valor['cantidad'] ?></div>
                    <div><a id="eliminarCarrito_<?php echo $index ?>" href="/carrito-compras/eliminar-producto/indice/<?php echo $index ?>" >Eliminar</a></div>
                </form>
            </li>
            <?php
            $precioTotal= $precioItem + $precioTotal;
        }
        ?>
            <li>
                <div>
                    <a href="/productos">Agregar mas Productos a mi carrito</a>
                </div>
                <div>
                    Total:<?php echo $precioTotal; ?>
                </div>
                <div>
                    <a href="/carrito-compras/medio-pago">Continuar Compra</a>
                </div>
                
            </li>
    </ul>
</div>