<html><head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js" type="text/javascript"></script>
</head>
<body>
    Redirec.....
<?php $arrayPackeges = $this->listingsSingleAgentPackages[$this->singleAgent['plansSelect']['checkSingleAgentPlans']][0]; ?>
<form name = "_xclick" id = "_xclick" action="https://<?php echo $this->hostPaypal ?>/cgi-bin/webscr" 
      method="post">
    <input type="hidden" name="cmd" value="_xclick">
    <input type="hidden" name="business" value="<?php echo $this->accountPaypal ?>">
    <input type="hidden" name="currency_code" value="USD">
    <input type="hidden" name="item_name" value="Productos">
    <input type="hidden" name="item_number" value="<?php echo $this->transaccion; ?>">
    <input type="hidden" name="amount" value="<?php echo $this->price; ?>">
    <input type="hidden" name="return" value="<?php echo $this->baseUrl() ?>/carrito-compras/confirmacion-pago/tr/<?php echo $this->transaccion; ?>">
</form>

<script>
    $(document).ready(function(){
        $('#_xclick').submit();
    })
</script>
</body>
</html>